info:
  contact: {}
paths:
  /DeFi/coins/:token:
    get:
      consumes:
      - application/json
      description: harvest coingecko data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: harvest coin price from coingecko
      tags:
      - example
  /health:
    get:
      consumes:
      - application/json
      description: ensure api is responding
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health
      tags:
      - example
swagger: "2.0"
